import type { Account, Transaction, Goal, Budget } from '@/types'

export const mockAccounts: Account[] = [
  {
    id: '1',
    name: 'Main Checking',
    type: 'checking',
    balance: 4250.75,
    currency: 'USD',
  },
  {
    id: '2',
    name: 'Emergency Savings',
    type: 'savings',
    balance: 12500.00,
    currency: 'USD',
  },
  {
    id: '3',
    name: 'Credit Card',
    type: 'credit',
    balance: -1850.32,
    currency: 'USD',
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    accountId: '1',
    account: 'Main Checking',
    category: 'Groceries',
    description: 'Whole Foods Market',
    amount: -127.45,
    type: 'expense',
    date: '2025-10-17',
    status: 'completed',
  },
  {
    id: '2',
    accountId: '1',
    account: 'Main Checking',
    category: 'Salary',
    description: 'Monthly Salary',
    amount: 5500.00,
    type: 'income',
    date: '2025-10-15',
    status: 'completed',
  },
  {
    id: '3',
    accountId: '3',
    account: 'Credit Card',
    category: 'Dining',
    description: 'Restaurant XYZ',
    amount: -89.32,
    type: 'expense',
    date: '2025-10-16',
    status: 'completed',
  },
  {
    id: '4',
    accountId: '1',
    account: 'Main Checking',
    category: 'Transportation',
    description: 'Gas Station',
    amount: -65.20,
    type: 'expense',
    date: '2025-10-16',
    status: 'completed',
  },
  {
    id: '5',
    accountId: '1',
    account: 'Main Checking',
    category: 'Entertainment',
    description: 'Movie Theater',
    amount: -24.99,
    type: 'expense',
    date: '2025-10-15',
    status: 'completed',
  },
  {
    id: '6',
    accountId: '2',
    account: 'Emergency Savings',
    category: 'Transfer',
    description: 'Monthly Savings',
    amount: 500.00,
    type: 'income',
    date: '2025-10-15',
    status: 'completed',
  },
  {
    id: '7',
    accountId: '1',
    account: 'Main Checking',
    category: 'Shopping',
    description: 'Amazon Purchase',
    amount: -156.78,
    type: 'expense',
    date: '2025-10-14',
    status: 'pending',
  },
  {
    id: '8',
    accountId: '1',
    account: 'Main Checking',
    category: 'Utilities',
    description: 'Electric Bill',
    amount: -142.50,
    type: 'expense',
    date: '2025-10-13',
    status: 'completed',
  },
]

export const mockGoals: Goal[] = [
  {
    id: '1',
    name: 'Emergency Fund',
    targetAmount: 15000,
    currentAmount: 12500,
    deadline: '2025-12-31',
    category: 'Savings',
    priority: 'high',
  },
  {
    id: '2',
    name: 'Vacation Fund',
    targetAmount: 3000,
    currentAmount: 1850,
    deadline: '2025-06-01',
    category: 'Travel',
    priority: 'medium',
  },
  {
    id: '3',
    name: 'New Laptop',
    targetAmount: 2500,
    currentAmount: 800,
    deadline: '2025-03-15',
    category: 'Technology',
    priority: 'low',
  },
]

export const mockBudgets: Budget[] = [
  {
    id: '1',
    category: 'Groceries',
    allocated: 600,
    spent: 427.45,
    period: 'monthly',
    startDate: '2025-10-01',
    endDate: '2025-10-31',
  },
  {
    id: '2',
    category: 'Dining',
    allocated: 300,
    spent: 189.32,
    period: 'monthly',
    startDate: '2025-10-01',
    endDate: '2025-10-31',
  },
  {
    id: '3',
    category: 'Transportation',
    allocated: 400,
    spent: 265.20,
    period: 'monthly',
    startDate: '2025-10-01',
    endDate: '2025-10-31',
  },
  {
    id: '4',
    category: 'Entertainment',
    allocated: 200,
    spent: 124.99,
    period: 'monthly',
    startDate: '2025-10-01',
    endDate: '2025-10-31',
  },
]
