version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: expense_tracker_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d:ro

  api:
    build:
      context: ./src/ExpenseTracker.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=postgres;Port=5432;Database=expense_tracker_dev;Username=postgres;Password=postgres
      - JWT_SECRET=replace_this_secret_for_dev
    depends_on:
      - postgres
    ports:
      - "5000:80"
    stdin_open: true
    tty: true

volumes:
  db-data:
